import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../models/planned_meal.dart';
import '../../../models/shopping_item.dart';

class PdfService {
  static Future<void> generateMealPlanPdf({
    required Map<String, List<PlannedMeal>> weeklyPlan,
    required List<ShoppingItem> shoppingList,
  }) async {
    final pdf = pw.Document();

    // Add a page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('FitKitchen Meal Prep Plan', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(DateTime.now().toString().substring(0, 10)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            
            pw.Text('Weekly Meal Plan', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            
            ...weeklyPlan.entries.map((entry) {
              if (entry.value.isEmpty) return pw.Container();
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.SizedBox(height: 10),
                  pw.Text(entry.key, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                  pw.Bullet(text: entry.value.map((m) => m.recipe.title).join(', ')),
                ],
              );
            }).toList(),

            pw.SizedBox(height: 30),
            pw.Text('Shopping List', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(),
            
            pw.TableHelper.fromTextArray(
              context: context,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              data: <List<String>>[
                <String>['Item', 'Qty', 'Unit', 'Category'],
                ...shoppingList.map((item) => [
                  item.name,
                  item.quantity.toString(),
                  item.unit,
                  item.category,
                ]),
              ],
            ),

            pw.Footer(
              padding: const pw.EdgeInsets.only(top: 20),
              trailing: pw.Text('Generated by FitKitchen App', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
            ),
          ];
        },
      ),
    );

    // Preview or Print
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'FitKitchen_Plan_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }
}
